# Generated by Django 3.2.18 on 2023-03-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230322_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='prod_photo',
        ),
    ]
