# Generated by Django 3.2.18 on 2023-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20230424_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vw_product',
            name='user',
        ),
    ]
