# Generated by Django 3.2.18 on 2023-04-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_vw_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vw_product',
            name='price_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
