# Generated by Django 3.2.18 on 2023-04-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_vw_product_price_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.AlterField(
            model_name='vw_product',
            name='category',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Vendor', 'Vendor')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Vw_category',
        ),
    ]
