# Generated by Django 3.2.18 on 2023-05-02 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20230425_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vw_product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=250),
        ),
    ]
