# Generated by Django 3.2.18 on 2023-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_vw_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vw_product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
